# Generated by Django 3.2.9 on 2022-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gdocs_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
