# Generated by Django 3.2.9 on 2021-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(choices=[('B', 'Buy'), ('D', 'Donation'), ('C', 'Course')], default='B', max_length=255),
        ),
    ]
