# Generated by Django 3.2.9 on 2022-02-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='socialtoken',
            unique_together={('app', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'uid')},
        ),
    ]
