# Generated by Django 3.2.9 on 2021-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minister',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='evangelism.Evangelism'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='evangelism.Evangelism'),
        ),
    ]
