# Generated by Django 3.2.9 on 2022-02-22 12:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(choices=[('PUB', 'Books'), ('FAR', 'Food'), ('TAI', 'Fabric Material'), ('CON', 'Construction Materials'), ('TIM', 'Timber'), ('MET', 'Metal'), ('CHE', 'Oils'), ('HER', 'Herbs')], default='TIM', max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_description', models.TextField(max_length=1024)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_of_kin_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_sold', models.DateTimeField()),
                ('preferred_payment_mode', models.CharField(choices=[('PUB', 'Books'), ('FAR', 'Food'), ('TAI', 'Fabric Material'), ('CON', 'Construction Materials'), ('TIM', 'Timber'), ('MET', 'Metal'), ('CHE', 'Oils'), ('HER', 'Herbs')], default='MPESA', max_length=50)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_code', models.CharField(max_length=255, null=True)),
                ('mpesa_till_number', models.CharField(blank=True, max_length=10, null=True)),
                ('mpesa_pay_bill_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_category', models.CharField(choices=[('BUS', 'Business'), ('FAR', 'Farming'), ('TAI', 'Tailoring'), ('CON', 'Construction Work'), ('WOO', 'Wood Work'), ('MET', 'Metal Work'), ('COO', 'Cooking'), ('CHE', 'Oils and Soap Making'), ('NAT', 'Healing and Herbal Mixing')], default='FAR', max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment', models.FileField(blank=True, null=True, upload_to='')),
                ('assignment_deadline', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('ending_time', models.DateTimeField(blank=True, null=True)),
                ('understood', models.BooleanField(default=False)),
                ('need_repeat', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_type', models.CharField(choices=[('WS', 'Work Study'), ('SSP', 'Self Sponsored')], default='WS', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=1024)),
                ('confirm_password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('completed_assignment', models.BooleanField(default=False)),
                ('probation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=1024)),
                ('confirm_password', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('probation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
