# Generated by Django 3.2.9 on 2022-02-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20220222_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessperson',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
