# Generated by Django 3.2.9 on 2022-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_businessperson_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_category',
            field=models.CharField(choices=[('BUS', 'Business'), ('FAR', 'Farming'), ('TAI', 'Tailoring'), ('CON', 'Construction Work'), ('WOO', 'Wood Work'), ('MET', 'Metal Work'), ('MUS', 'Music'), ('COO', 'Cooking'), ('CHE', 'Oils and Soap Making'), ('NAT', 'Healing and Herbal Mixing')], default='FAR', max_length=50),
        ),
    ]
